version: 1.1.{build}

image: Visual Studio 2017

branches:
  only:
  - master

configuration: Release
platform: x64
#clone_depth: 5
# specific to github and bitbucket: get a ZIP file using REST API
shallow_clone: true


init:
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
- curl -LsSO http://ffmpeg.zeranoe.com/builds/win64/dev/ffmpeg-3.3.1-win64-dev.zip
- 7z x ffmpeg-3.3.1-win64-dev.zip -o.
- mkdir C:\Dev\
- mkdir C:\Dev\ffmpeg-win64-dev
- move ffmpeg-3.3.1-win64-dev\lib C:\Dev\ffmpeg-win64-dev
- move ffmpeg-3.3.1-win64-dev\include C:\Dev\ffmpeg-win64-dev
- del /Q *.zip
- rmdir /Q /S ffmpeg-3.3.1-win64-dev
- dir C:\Dev
- dir C:\Dev\ffmpeg-win64-dev\include
- dir C:\Dev\ffmpeg-win64-dev\lib
- ps: Get-NodeJsLatestBuild 6.0

environment:
  BITBUCKET_PASSWORD:
    secure: knMJcKTWQPaMlmpY298Z4w==
  matrix:
  - nodejs_version: 8.9.4
  - nodejs_version: 9.9.0
  - nodejs_version: 10.9.0

install:
- ps: >-
    Install-Product node $env:nodejs_version x64

    npm -v

    node -v

    npm config set package-lock=false

    npm config set save=false

    npm install --msvs_version=2017

    npm run rebuild

build:
  parallel: true
  verbosity: minimal

after_build:
- curl -LsSO http://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-3.3.1-win64-shared.zip
- 7z x ffmpeg-3.3.1-win64-shared.zip -o.
- move ffmpeg-3.3.1-win64-shared\bin\* build\Release
- rmdir /Q /S ffmpeg-3.3.1-win64-shared
- del /Q *.zip
- mkdir C:\Build\
#- 7z a -ttar  C:\Build\node-demux_win_%nodejs_version%.tar    C:\projects\node-demux\
#- 7z a -tgzip C:\Build\node-demux_win_%nodejs_version%.tar.gz C:\Build\node-demux_win_%nodejs_version%.tar
- 7z a -ttar  C:\Build\node_demux-v1.1.0-node-v%nodejs_version%-win32-x64.tar    C:\projects\node-demux\build\Release
- 7z a -tgzip C:\Build\node_demux-v1.1.0-node-v%nodejs_version%-win32-x64.tar.gz C:\Build\node_demux-v1.1.0-node-v%nodejs_version%-win32-x64.tar
#- move C:\Build\node-demux_win_%nodejs_version%.tar.gz C:\projects\node-demux
- move C:\Build\node_demux-v1.1.0-node-v%nodejs_version%-win32-x64.tar.gz C:\projects\node-demux
#- curl --insecure --progress-bar --location --fail --user "renambot:%BITBUCKET_PASSWORD%" --form files=@"node-demux_win_%nodejs_version%.tar.gz" "https://api.bitbucket.org/2.0/repositories/sage2/binaries/downloads/"
- curl --insecure --progress-bar --location --fail --user "renambot:%BITBUCKET_PASSWORD%" --form files=@"node_demux-v1.1.0-node-v%nodejs_version%-win32-x64.tar.gz" "https://api.bitbucket.org/2.0/repositories/sage2/binaries/downloads/"
- dir

test: off
